gardener/falco-event-ingestor

hack/db/setup_db.sql
Priority column too narrow. Fixes formatting when converting from table
```feature user
```
=> Convert char columns to varchar

chart/templates/_helpers.yaml, chart/templates/ingestor-deployment.yaml, chart/templates/ingestor-ingress.yaml, chart/templates/ingestor-secret.yaml, chart/templates/ingestor-service.yaml, chart/templates/intestor-vpa.yaml, chart/values.yaml, pkg/postgres/postgres.go
=> Deploy updates

chart/templates/ingestor-ingress.yaml
=> Rename ingestor tls secret

chart/values.yaml, pkg/server/server.go
=> Raise rate limits for testing

charts/falco-event-ingestor/templates/ingestor-service.yaml
=> Allow external traffic to ingestor

pkg/metrics/metrics.go, pkg/server/server.go
=> Switch to hist metric type

charts/falco-event-ingestor/templates/ingestor-service.yaml, charts/falco-event-ingestor/templates/ingestor-servicemonitor.yaml
Add prometheus scraping- and networking config
Fixes #
```feature user
```
=> Add prometheus scraping- and networking config

charts/falco-event-ingestor/templates/ingestor-deployment.yaml, charts/falco-event-ingestor/templates/ingestor-secret.yaml
Add ability to store multiple public keys enabling jwt verification key rotation
Fixes #
```feature user
```
=> Add ability to handle multiple jwt verification keys

charts/falco-event-ingestor/templates/ingestor-deployment.yaml, cmd/ingestor/main.go, go.mod, pkg/auth/validation.go, pkg/auth/validation_test.go
Verify jwt with primary and secondary key for key rotation
Fixes #
```feature user
```
=> Added two key verification

.ci/pipeline_definitions
=> Bootstrap new updated pipeline image

.ci/pipeline_definitions
=> Reverted back to previous pipeline image due to go linter restrictions

go.mod
=> Update go version to 1.22.3

.ci/pipeline_definitions
=> Update pipeline image to go 1.23.3

.ci/pipeline_definitions, go.mod, hack/tools/tools.mk, pkg/server/server.go
=> Update go version to 1.23.3

.ci/pipeline_definitions, .gitignore, Makefile, cmd/ingestor/main.go, hack/sast.sh, hack/tools/install-gosec.sh, hack/tools/tools.mk, pkg/auth/validation.go, pkg/server/server.go
=> Introduce `gosec` for Static Application Security Testing (SAST)

pkg/metrics/metrics.go, pkg/postgres/postgres.go, pkg/server/server.go
Provides metrics for failed and successful inserts
Addresses https://github.com/gardener/falco-event-ingestor/issues/21
```feature user
```
=> Provide metrics for insert failure and success

charts/falco-event-ingestor/templates/ingestor-deployment.yaml
Deployments need to be rolled after for every deployment due to possible key rotations
Fixes #
```feature user
```
=> Force deployment rolling

.ci/pipeline_definitions
=> Bump golang-1.23.6 ci image

.ci/pipeline_definitions
=> Update verify image golang 1.24.1

charts/falco-event-ingestor/templates/ingestor-deployment.yaml
=> Disallow privilege escalation

charts/falco-event-ingestor/templates/ingestor-deployment.yaml
=> Disallow privilege escalation in right location

charts/falco-event-ingestor/templates/ingestor-deployment.yaml
=> Remove ineffectual pod label

charts/falco-event-ingestor/values.yaml
=> Remove resource limit

.ci/pipeline_definitions
=> Update go image in verify

pkg/postgres/postgres.go
=> Switch cluster uuid to falco event uuid

.ci/pipeline_definitions, go.mod
=> Update golang to 1.24.3

charts/falco-event-ingestor/templates/ingestor-deletion-job.yaml
Fixes failing liveness probe and resulting frequent pod restarts
```feature user
```
=> Remove failing liveness probe from deletion job

pkg/postgres/postgres.go
=> Increase jsonb to 50 kib to accomodate larger cmds
